### PR TITLE
fix: solidify handling of scoped packages

### LINKED ISSUE #38: bug: direct navigation to scoped packages is broken
For example, `@supabase/node-fetch`, navigating from main page works

Image<br>

Image<br>

But direct navigation to https://replacements.fyi/%40supabase%2Fnode-fetch is broken (404)

Image<br>

### PR DESCRIPTION
**Pull request by paoloricciuti**
Closes #38

I've also took the opportunity to make the routing structure a bit more solid without duplicating the logic.

### CODE REVIEW

File: src/routes/packages/+page.svelte [hunk 1]
```diff
@@ -40,7 +41,7 @@
 					onclick={(e) => {
 						e.currentTarget.style.setProperty('view-transition-name', 'package-name');
 					}}
-					href={resolve('/[package]', { package: encodeURIComponent(pkg) })}
+					href={resolve('/[[scope=scope]]/[package]', scopify(pkg))}
```
Comment (43081j) [inline src/routes/packages/+page.svelte:44]: this is no longer encoded, is that because svelte does it?

File: src/routes/[package].json/+server.ts [hunk 2]
```diff
@@ -1,22 +0,0 @@
...
-export const GET: RequestHandler = ({ params }) => {
-	const name = params.package;
-	if (!name || !Object.hasOwn(all.mappings, name)) {
-		throw error(404, `No replacement found for "${name}"`);
-	}
-	const mapping = all.mappings[name];
-
-	const replacements = mapping.replacements.map((key) => all.replacements[key]);
-
-	return json({
```
Comment (43081j) [inline src/routes/[package].json/+server.ts:16]: what does this now?

File: src/routes/packages/+page.svelte (hunk 1 above)
Comment (paoloricciuti) [reply src/routes/packages/+page.svelte:44]: Nope is because the reason I needed the encoding was to prevent this very problem...if we use the route approach it's not needed anymore.

File: src/routes/[package].json/+server.ts (hunk 2 above)
Comment (paoloricciuti) [reply src/routes/[package].json/+server.ts:16]: the other page with an optional `[[scope=scope]]` parameter

File: src/routes/packages/+page.svelte (hunk 1 above)
Comment (43081j) [reply src/routes/packages/+page.svelte:44]: i guess what i meant was that `package` could contain `/` for example.

but it can't in real world since no npm package can look like that. so i think this is fine

**Review by 43081j — APPROVED** [review]
